Sync {
  Mode ${SYNC_MODE} {
    DisableExternalCache Off
    StartupResync On
  }

  UDP {
    IPv4_address ${IPV4_ADDRESS}
    IPv4_Destination_Address ${IPV4_DESTINATION_ADDRESS}
    Port ${SYNC_PORT}
    Interface ${INTERFACE}
    SndSocketBuffer 1249280
    RcvSocketBuffer 1249280
    Checksum on
  }
}

General {
  HashSize ${HASH_SIZE}
  HashLimit ${HASH_LIMIT}
  LogFile off
  Syslog on
  LockFile /var/lock/conntrackd.lock
  UNIX {
    Path ${SOCKET_PATH}
  }
  NetlinkBufferSize 2097152
  NetlinkBufferSizeMaxGrowth 8388608
  Filter From Userspace {
    Protocol Accept {
      TCP
      UDP
    }
    Address Ignore {
      IPv4_address 127.0.0.1
      IPv4_address ${IPV4_ADDRESS}
      IPv4_address ${IPV4_DESTINATION_ADDRESS}
    }
  }
}
